# -*- coding: utf-8 -*-
"""Challenge2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Jdjq6UpHyC0S0ze3f4LEv0Ch2DGMnfq
"""

def spiral_order(matrix):
    result = []

    if not matrix or not matrix[0]:
        return result

    rows = len(matrix)
    cols = len(matrix[0])

    top, bottom = 0, rows - 1
    left, right = 0, cols - 1

    while top <= bottom and left <= right:

        # left → right (top row)
        for i in range(left, right + 1):
            result.append(matrix[top][i])
        top += 1

        # top → bottom (right column)
        for i in range(top, bottom + 1):
            result.append(matrix[i][right])
        right -= 1

        # right → left (bottom row)
        if top <= bottom:
            for i in range(right, left - 1, -1):
                result.append(matrix[bottom][i])
            bottom -= 1

        # bottom → top (left column)
        if left <= right:
            for i in range(bottom, top - 1, -1):
                result.append(matrix[i][left])
            left += 1

    return result


matrix = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
]

print(spiral_order(matrix))